### ISSUE TITLE
Blurry?

### ISSUE THREAD

**Issue by owhs** [RandomGamingDev/GLTilemapp5js#1]
Hi even with your 

      this.tiles.setInterpolation(this.gl.NEAREST, this.gl.NEAREST);
lines, i was still getting a blurry image in the ouput

at the top, where you "load parameters"
under the line

           this.img.texture = canvas.getTexture(this.img);

if i put

    this.img.texture.setInterpolation(NEAREST, NEAREST);

it works as intended :)

so for my use, i just added it as an argument after the tileList:

     constructor(pos, size, res, img, tilemapData, tilesList, nearest=false,
                 shad = createShader(GLTilemap.vertShader, GLTilemap.fragShader),
                 fbo, rdr = window, canvas = _renderer) {
       { // Load parameters
         ...
         this.img.texture = canvas.getTexture(this.img);
         if (nearest) this.img.texture.setInterpolation(NEAREST, NEAREST);
         ....
       }

so for me it's not an issue, but i didn't want to submit a PR in case there are issues with my solution, maybe put the argument at the end, ie for compatibility.

**Comment by RandomGamingDev** [comment]
Yeah, that may look like an issue, but the library isn't meant to modify the tilemap's texture atlas so it's up to the user themselves to set it to `NEAREST` since, after all, it'd be pretty weird to have an image you set to `LINEAR` be set to `NEAREST` just because it was set as the atlas for a tilemap.
